import { AdminService } from '$lib/application/admin.service';
import { AuthService } from '$lib/application/auth.service';
import { ProfileService } from '$lib/application/profile.service';
import { ConsumptionService } from '$lib/application/consumption.service';
import { ShoppingListService } from '$lib/application/shopping-list.service';
import { InventoryService } from '$lib/application/inventory.service';
import { MealPlanService } from '$lib/application/meal-plan.service';
import { PetFoodService } from '$lib/application/pet-food.service';
import { PetService } from '$lib/application/pet.service';
import { DrizzleMealPlanRepository } from '$lib/infrastructure/repositories/meal-plan.repository';
import { DrizzlePetFoodRepository } from '$lib/infrastructure/repositories/pet-food.repository';
import { DrizzlePetRepository } from '$lib/infrastructure/repositories/pet.repository';
import { HouseholdService } from '$lib/application/household.service';
import { DrizzleHouseholdRepository } from '$lib/infrastructure/repositories/household.repository';
import { DrizzleShoppingListRepository } from '$lib/infrastructure/repositories/shopping-list.repository';
import { DrizzleInventoryRepository } from '$lib/infrastructure/repositories/inventory.repository';
import { DrizzleAdminRepository } from '$lib/infrastructure/repositories/admin.repository';
import { DrizzleErrorLogRepository } from '$lib/infrastructure/repositories/error-log.repository';
import { DrizzleUserRepository } from '$lib/infrastructure/repositories/user.repository';

const userRepository = new DrizzleUserRepository();
const errorLogRepository = new DrizzleErrorLogRepository();
const adminRepository = new DrizzleAdminRepository(errorLogRepository);
const householdRepository = new DrizzleHouseholdRepository();
const inventoryRepository = new DrizzleInventoryRepository();
const consumptionRepository = new DrizzleConsumptionRepository();
const shoppingListRepository = new DrizzleShoppingListRepository();
const mealPlanRepository = new DrizzleMealPlanRepository();
const petRepository = new DrizzlePetRepository();
const petFoodRepository = new DrizzlePetFoodRepository();

export const authService = new AuthService(userRepository);
export const profileService = new ProfileService(userRepository);
export const adminService = new AdminService(adminRepository);
export const householdService = new HouseholdService(householdRepository);
export const consumptionService = new ConsumptionService(consumptionRepository);
export const inventoryService = new InventoryService(inventoryRepository, consumptionService);
export const shoppingListService = new ShoppingListService(shoppingListRepository);
export const mealPlanService = new MealPlanService(mealPlanRepository);
export const petService = new PetService(petRepository);
export const petFoodService = new PetFoodService(petFoodRepository);
