/**
 * Generates brand-colors.generated.css and SCSS variables from brand-colors.ts.
 * Active track: BRAND_PALETTE env (default fresh).
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
	type BrandColorMode,
	type BrandPalette,
	type PaletteTrack,
	getLearningAiGradientStops,
	LOCKED_LOGO_CORE,
	mergePalette,
	toCssCustomProperties
} from '../src/lib/design/brand-colors.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const CSS_OUT = resolve(ROOT, 'src/lib/design/brand-colors.generated.css');
const SCSS_LIGHT_OUT = resolve(ROOT, 'src/theme/brand-variables.generated.scss');
const SCSS_DARK_OUT = resolve(ROOT, 'src/theme/dark/brand-variables.generated.scss');

const VALID_TRACKS: PaletteTrack[] = ['heritage', 'fresh', 'warm', 'crisp'];

function resolveTrack(): PaletteTrack {
	const raw = (process.env.BRAND_PALETTE ?? 'fresh').toLowerCase();
	if (VALID_TRACKS.includes(raw as PaletteTrack)) return raw as PaletteTrack;
	console.warn(`Unknown BRAND_PALETTE "${raw}", falling back to fresh`);
	return 'fresh';
}

function cssDeclBlock(vars: Record<string, string>, indent = '\t'): string {
	return Object.entries(vars)
		.map(([name, value]) => `${indent}${name}: ${value};`)
		.join('\n');
}

function buildToastVars(palette: BrandPalette, mode: BrandColorMode): Record<string, string> {
	if (mode === 'light') {
		return {
			'--toast-bg': palette.text,
			'--toast-fg': palette.onPrimary,
			'--toast-fg-muted': 'rgba(255, 255, 255, 0.88)',
			'--toast-dismiss-hover': 'rgba(255, 255, 255, 0.14)',
			'--toast-icon-bg': 'rgba(255, 255, 255, 0.2)'
		};
	}
	return {
		'--toast-bg': `color-mix(in srgb, ${palette.text} 18%, ${palette.surface})`,
		'--toast-fg': palette.bg,
		'--toast-fg-muted': `color-mix(in srgb, ${palette.bg} 82%, transparent)`,
		'--toast-dismiss-hover': `color-mix(in srgb, ${palette.bg} 10%, transparent)`,
		'--toast-icon-bg': `color-mix(in srgb, ${palette.bg} 14%, transparent)`
	};
}

function buildLearningAiGradientVar(track: PaletteTrack): string {
	const stops = getLearningAiGradientStops(track).join(', ');
	return `linear-gradient(110deg, ${stops})`;
}

function buildCss(track: PaletteTrack): string {
	const palette = mergePalette(track);
	const lightVars = {
		...toCssCustomProperties(palette.light, 'light'),
		...buildToastVars(palette.light, 'light'),
		'--color-learning-ai-gradient': buildLearningAiGradientVar(track)
	};
	const darkVars = {
		...toCssCustomProperties(palette.dark, 'dark'),
		...buildToastVars(palette.dark, 'dark'),
		'--color-learning-ai-gradient': buildLearningAiGradientVar(track)
	};

	return `/* Generated by scripts/generate-brand-css.mts — do not edit manually */
/* Track: ${track} — set BRAND_PALETTE at build time */

:root {
${cssDeclBlock(lightVars)}
}

html[data-theme='dark'] {
${cssDeclBlock(darkVars)}
}
`;
}

function scssBlock(palette: BrandPalette, mode: BrandColorMode): string {
	const radius = { sm: '8px', md: '12px', lg: '16px' };
	return `// Generated — track palette (${mode})
$skaffu-primary: ${palette.primary};
$skaffu-primary-hover: ${palette.primaryHover};
$skaffu-surface: ${palette.surface};
$skaffu-surface-muted: ${palette.surfaceMuted};
$skaffu-background: ${palette.bg};
$skaffu-on-surface: ${palette.text};
$skaffu-on-surface-muted: ${palette.textMuted};
$skaffu-error: ${palette.danger};
$skaffu-border: ${palette.border};
$skaffu-success: ${palette.success};
$skaffu-warning: ${palette.warning};
$skaffu-info: ${palette.info};
$skaffu-accent: ${palette.accent};
$skaffu-secondary: ${palette.secondary};
$skaffu-fridge: ${palette.fridge};
$skaffu-freezer: ${palette.freezer};
$skaffu-cupboard: ${palette.cupboard};
$skaffu-learning-ai: ${palette.learningAi};

$skaffu-radius-sm: ${radius.sm};
$skaffu-radius-md: ${radius.md};
$skaffu-radius-lg: ${radius.lg};

$skaffu-font-family: 'DM Sans', system-ui, sans-serif;
`;
}

async function syncLockedBrandSvgs(): Promise<void> {
	const L = LOCKED_LOGO_CORE.light;
	const markInner = `<rect width="32" height="32" rx="8" fill="${L.primary}"/>
  <path fill="${L.onPrimary}" d="M16 8.5 9.5 13.2V22a1.2 1.2 0 0 0 1.2 1.2h3.1v-4.2h4.4v4.2h3.1A1.2 1.2 0 0 0 22.5 22v-8.8L16 8.5Z"/>
  <path d="M11.8 17.2h8.4" stroke="${L.surfaceMuted}" stroke-width="1.35" stroke-linecap="round" fill="none"/>
  <rect x="20.8" y="10.8" width="4.2" height="4.2" rx="1" fill="${L.accent}"/>`;

	const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="none">
  ${markInner}
</svg>
`;
	await writeFile(resolve(ROOT, 'static/favicon.svg'), favicon, 'utf8');
	await writeFile(resolve(ROOT, 'static/pwa/icon.svg'), favicon, 'utf8');
}

async function main(): Promise<void> {
	const track = resolveTrack();
	const css = buildCss(track);
	const lightScss = scssBlock(mergePalette(track).light, 'light');
	const darkScss = scssBlock(mergePalette(track).dark, 'dark');

	await mkdir(dirname(CSS_OUT), { recursive: true });
	await mkdir(dirname(SCSS_DARK_OUT), { recursive: true });
	await writeFile(CSS_OUT, css, 'utf8');
	await writeFile(SCSS_LIGHT_OUT, lightScss, 'utf8');
	await writeFile(SCSS_DARK_OUT, darkScss, 'utf8');
	await syncLockedBrandSvgs();

	console.log(`Generated brand CSS (track=${track}):`);
	console.log(`  ${CSS_OUT}`);
	console.log(`  ${SCSS_LIGHT_OUT}`);
	console.log(`  ${SCSS_DARK_OUT}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
