import { batchCustomId } from '$lib/domain/ai-batch';
import type {
	ExpiryReminderService,
	PrebatchedPushBodyProvider
} from '$lib/application/expiry-reminder.service';
import type { IAiBatchJobRepository } from '$lib/infrastructure/repositories/ai-batch-job.repository';
import {
	buildExpiryPushUserPrompt,
	EXPIRY_PUSH_BODY_SCHEMA,
	EXPIRY_PUSH_MAX_ITEMS,
	EXPIRY_PUSH_SCHEMA_NAME,
	EXPIRY_PUSH_SYSTEM_PROMPT,
	expiryPushBodyKey,
	type ExpiryPushItem
} from '$lib/server/expiry-push-prompt';
import { isBrainProactiveEnabled } from '$lib/server/feature-flags';
import { buildStructuredRequestBody, OPENAI_MODEL_NANO } from '$lib/server/openai';
import type { BatchOutputLine, BatchRequestLine } from '$lib/server/openai-batch';
import type { AiBatchApplyResult, AiBatchCollectResult, AiBatchKindHandler } from './types';
import { isUsableOutputLine } from './types';

const PUSH_BODY_MAX_CHARS = 120;
const PREBATCHED_LOOKBACK_MS = 3 * 24 * 60 * 60 * 1000;
/**
 * Pre-generate only on Sunday (UTC), the day before the weekly expiry-reminder
 * cron (Monday 07:00 UTC, expiry-reminders-cron.yml). The consumer is weekly, so
 * daily generation would cost more than the synchronous status quo.
 */
const WEEKLY_PREGEN_UTC_DAY = 0;

interface ExpiryPushPayload {
	targets: Record<string, { key: string }>;
}

interface ExpiryPushResult {
	bodies: Record<string, string>;
}

/**
 * Pre-generates the weekly expiry-reminder push body for each push-enabled user
 * via Batch API, keyed by recipient + item set. The reminder cron reads these at
 * send time (see PrebatchedPushBodyProvider); a cache miss falls back to the
 * synchronous nano call, so freshness is never blocked on the batch.
 */
export function createExpiryPushBatchHandler(deps: {
	expiryReminderService: Pick<ExpiryReminderService, 'collectWeeklyPushPredictions'>;
	now?: () => Date;
}): AiBatchKindHandler {
	return {
		kind: 'expiry_push',
		minResubmitHours: 18,

		isEnabled: () => isBrainProactiveEnabled(),

		async collect(): Promise<AiBatchCollectResult | null> {
			const now = deps.now?.() ?? new Date();
			if (now.getUTCDay() !== WEEKLY_PREGEN_UTC_DAY) return null;

			const predictions = await deps.expiryReminderService.collectWeeklyPushPredictions();
			if (predictions.length === 0) return null;

			const lines: BatchRequestLine[] = [];
			const targets: Record<string, { key: string }> = {};

			for (const prediction of predictions) {
				const customId = batchCustomId('expiry_push', lines.length);
				targets[customId] = { key: prediction.key };
				lines.push({
					customId,
					body: buildStructuredRequestBody({
						model: OPENAI_MODEL_NANO,
						systemPrompt: EXPIRY_PUSH_SYSTEM_PROMPT,
						userPrompt: buildExpiryPushUserPrompt(prediction.items, 'sv'),
						schemaName: EXPIRY_PUSH_SCHEMA_NAME,
						schema: EXPIRY_PUSH_BODY_SCHEMA as unknown as Record<string, unknown>
					})
				});
			}

			const payload: ExpiryPushPayload = { targets };
			return { lines, payload: payload as unknown as Record<string, unknown> };
		},

		async apply(
			lines: BatchOutputLine[],
			rawPayload: Record<string, unknown>
		): Promise<AiBatchApplyResult> {
			const payload = rawPayload as unknown as ExpiryPushPayload;
			const bodies: Record<string, string> = {};

			for (const line of lines) {
				if (!isUsableOutputLine(line) || line.json === null) continue;
				const key = payload.targets?.[line.customId]?.key;
				if (!key) continue;
				const body = (line.json as { body?: unknown }).body;
				if (typeof body !== 'string') continue;
				const trimmed = body.trim();
				if (trimmed) bodies[key] = trimmed.slice(0, PUSH_BODY_MAX_CHARS);
			}

			const result: ExpiryPushResult = { bodies };
			return { applied: Object.keys(bodies).length, result: result as unknown as Record<string, unknown> };
		}
	};
}

/**
 * Reads push bodies pre-generated by the expiry_push batch handler. Injected into
 * ExpiryReminderService so the weekly reminder consumes the discounted bodies.
 */
export function createPrebatchedPushBodyProvider(
	aiBatchJobRepository: Pick<IAiBatchJobRepository, 'listRecentApplied'>
): PrebatchedPushBodyProvider {
	return {
		async get(userId: string, items: ExpiryPushItem[]): Promise<string | null> {
			if (items.length === 0) return null;
			const key = expiryPushBodyKey(userId, items.slice(0, EXPIRY_PUSH_MAX_ITEMS));
			const since = new Date(Date.now() - PREBATCHED_LOOKBACK_MS);
			const jobs = await aiBatchJobRepository.listRecentApplied('expiry_push', since);
			for (const job of jobs) {
				const bodies = (job.result as ExpiryPushResult | null)?.bodies;
				const body = bodies?.[key];
				if (typeof body === 'string' && body.trim()) {
					return body;
				}
			}
			return null;
		}
	};
}
