import { existsSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

export const ROOT = resolve(__dirname, '../..');
export const DESIGN_DIR = join(ROOT, 'design');
export const SCREENSHOTS_DIR = join(DESIGN_DIR, 'SCREENSHOTS');
export const FLOWS_DIR = join(DESIGN_DIR, 'FLOWS');
export const COMPONENTS_DIR = join(DESIGN_DIR, 'COMPONENTS');
export const ILLUSTRATIONS_DIR = join(DESIGN_DIR, 'ILLUSTRATIONS');

export const BRAND_CSS = join(ROOT, 'src/lib/design/brand-colors.generated.css');
export const TOKENS_CSS = join(ROOT, 'src/lib/design/brand-tokens.generated.css');
export const BRAND_COLORS_TS = join(ROOT, 'src/lib/design/brand-colors.ts');
export const DOCS_BRAND = join(ROOT, 'docs/BRAND.md');
export const DOCS_UX = join(ROOT, 'docs/UX_GUIDELINES.md');

export const MOBILE_VIEWPORT = { width: 390, height: 844 };

export function getBaseUrl(): string {
	return process.env.PLAYWRIGHT_BASE_URL ?? process.env.DESIGN_KIT_BASE_URL ?? 'http://localhost:5173';
}

/** Prefer explicit env, then E2E port (5190, Turnstile bypass), then default dev (5173). */
export async function resolveDesignKitBaseUrl(): Promise<string> {
	const explicit = process.env.DESIGN_KIT_BASE_URL ?? process.env.PLAYWRIGHT_BASE_URL;
	if (explicit) {
		return explicit.replace(/\/$/, '');
	}

	for (const port of [5190, 5173]) {
		const url = `http://localhost:${port}`;
		if (await isServerUp(url)) {
			return url;
		}
	}

	return 'http://localhost:5173';
}

export function ensureDir(path: string): void {
	if (!existsSync(path)) {
		mkdirSync(path, { recursive: true });
	}
}

export async function isServerUp(baseURL = getBaseUrl()): Promise<boolean> {
	try {
		const response = await fetch(baseURL, { signal: AbortSignal.timeout(5_000) });
		return response.status < 500;
	} catch {
		return false;
	}
}

export function generatedHeader(source: string): string {
	return `<!-- AUTO-GENERATED by scripts/design-kit — do not edit manually. Source: ${source} -->\n\n`;
}

export function isDirectScriptRun(): boolean {
	return Boolean(process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href);
}
